version: '3'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env 
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  web:
    build: .
    command:   python3 manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db